# Generated by Django 4.1.2 on 2022-10-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('options', models.CharField(max_length=50)),
            ],
        ),
    ]
