# Generated by Django 4.1.2 on 2022-10-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
