# Generated by Django 4.1.2 on 2022-10-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_item_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='days',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
